### ISSUE TITLE
Where did the preview/edit button go?

### ISSUE THREAD

**Issue by mockey** [hirokiky/pilemd#20]
Hi.

Nice Note App.
I just updated to 0.9.0 (on Linux64). There is no preview/edit button anymore? Have to use Alt+P now?

**Comment by hirokiky** [comment]
Yes. I removed it. 
I want the edit area to be more like preview (by showing images on the area and so on). I think the preview page is optional one.
Now the edit area and the UI are not perfect, but I want some another way, instead of preview and the toggle button. so I firstly removed the button.

NNow Please use Alt+P. I want any suggestion and patches to improve the ediror.

Thanks for using!

**Comment by mockey** [comment]
> Now the edit area and the UI are not perfect, but I want some another way, instead of preview and the toggle button. so I firstly removed the button.

I see. I was just wondering where it went. I liked it better than Alt+P, though.
